### ISSUE TITLE
Attribute directives apply for everything in an application

### ISSUE THREAD

**Issue by v1v2r0b8** [tombatossals/angular-leaflet-directive#1031]
Hello!

I think it was supposed that all inner _attribute_ directives would apply only to a parent `<leaflet>` _element_ directive, but they are invoked everywhere, e.g. in angular-google-maps directive (which causes the following error: `Controller 'leaflet', required by directive 'center', can't be found!`).  As a workaround, I deleted `'center'` from the line 3365:

``` javascript
var centerDirectiveTypes = ['center', 'lfCenter'];
```

but I think it's better to find a way to prevent invoking constructors for all such directives if an element is not a `<leaflet>`.

**Comment by jnystrom** [comment]
I am also seeing this error when I am using angular-google-maps directive.

**Comment by st04** [comment]
I thought this was fixed in #914 with the alternative lf-center by @nmccready ? 

EDIT: I too am having the same problem. Not so sure if the problem is related to the issue I stated above.

**Comment by jnystrom** [comment]
@st04 when I did what @leitasat suggested above...it worked for me...so the issue still exists.

**Comment by nimeso** [comment]
+1
This is also a issue when using 'bounds'. It clashes with google maps as well
angular.js:13550 Error: [$compile:ctreq] Controller 'leaflet', required by directive 'bounds', can't be found!
