### ISSUE TITLE
leaflet.label compiling only onclick

### ISSUE THREAD

**Issue by lleoooell** [tombatossals/angular-leaflet-directive#666]
Hello,

First, thanks for this awesome directive !

I'm running something strange and i cannot find a solution.

I'm running angular-leaflet in a MEAN stack app and everything work perfectly.

I have 4 markers with option "getMessageScope: function() {return $scope; }," to let me use a ng-click directive in popup and its ok. by default, focus is set on false.

I want also have a leaflet.label with "nohide:true" and a custom class on the right of the marker and bind some content in the label. 

Problem is, on page load, my labels are visible but the data content seems to be binded only when i click on the marker... Il i want it to be compiled on page load, i have to set my popup option focus to true. and i don't want that.

I want my popup hidden by default and my label visible with data binding by deflault...can someone knows how can i solve this ?

```
 m4: {
                        lat: 48.180913,
                        lng: 6.445758,
                         message: '<button style="width:100%" class=\'btn btn-tech\' ng-click="createAlert(\'input\')">Clic me ! </button>',
		    			getMessageScope: function() {return $scope; },
                        focus: false,
                        icon: local_icons.myicon,
                        label: {
                            message: '<div> <p data-ng-bind="array.length"></p></div>',
                            options: {
                                noHide: true,
                                className : "customClass"
                            }
                        }
                    },
```

**Comment by jessertaylor** [comment]
I have fixed this in the master (it's not in the release yet). Check that out, you can also now use:

```
getLabelScope: function() { return $scope }
```

**Comment by lleoooell** [comment]
Thanks a lot, you're my hero !!! ^^
I'll try this and let you know.

**Comment by nickolas1** [comment]
this is probably related to #657 as well, but I notice that when using Leaflet.markercluster the `$compile` call in `_manageOpenLabel` will often be called when there is no `marker.label._container` if a marker is part of a cluster. In this case the message is never successfully compiled, and when the marker is revealed any binding is not functional.

**Comment by jessertaylor** [comment]
@nickolas1 I have looked at your plunkr and have used the current dist that has my changes to the labels in.

It appears to function better, as in the labels are actually being compiled atleast. However I can see if you do click on a marker within a cluster the label is not compiled.

I will be using some of this functionality so I will more than likely have to fix it.

**Comment by lleoooell** [comment]
@jessertaylor , update : 

awesome !!! works perfect, tested with last commit version ! Thanks a lot !

```javascript
markers: {
                    
                    m2: {
                        lat: 49.120359,
                        lng: 6.173937,
                        message: 'goooood',
		    			getMessageScope: function() {return $scope; },
		    			getLabelScope: function() { return $scope },
                        focus: false,
                        // icon: local_icons.metz,
                        label: {
                            message: '<button ng-click="var2 = var2 + 1">Say Hello</button>',
                            options: {
                                noHide: true,
                                className : "class1"
                            }
                            
                        }
                    },
                    m3: {
                        lat: 49.358059,
                        lng: 6.167519,
                        message: 'gooood',
		    			getMessageScope: function() {return $scope; },
		    			getLabelScope: function() { return $scope },
                        focus: false,
                        // icon: local_icons.thionville,
                        label: {
                            message: '{{var2}}',
                            options: {
                                noHide: true,
                                className : "class2"
                            },
                        }
                    }
                }
```

**Comment by jessertaylor** [comment]
@lleoooell 

that great. @nmccready did some work on it aswell, team effort!

**Comment by nmccready** [comment]
This is resolved right?

**Comment by jessertaylor** [comment]
@nmccready Yes

**Comment by durga-telsiz** [comment]
@jessertaylor 
Thanks for the fix. Label picks up scope data only if it noHide is set to true. This issue still exists if noHide is set to false. On mouse over, label doesn't have compiled data.

**Comment by jessertaylor** [comment]
@durga-telsiz please could you provide an example / plunkr using master? Thanks

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#149

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
