### ISSUE TITLE
markers lng lat does not get updated if it is moved

### ISSUE THREAD

**Issue by jessertaylor** [tombatossals/angular-leaflet-directive#690]
Logging this, will come back and explain in more detail / plunkr

To reproduce:

Add marker with icon at 0,0

Drag marker to 100,100

Change icon of marker

Marker jumps back to 0,0

I was under the impression I shouldn't have to update the marker object coordinates myself after I've dragged it or am I mistaken? The directive should listen for drag events and update the markers object (angular) in question accordingly.

**Comment by jessertaylor** [comment]
maybe a dupe of #685

**Comment by samuelpfchoi** [comment]
Agree, the root cause of the both #685 & #690 issues are same. My finding:
After leaflet marker moved, the new position without updated to markerData but it is still being watched. Meanwhile, the properties of markerData is modified, the changes including old position will be applied to leaflet marker and cause the marker jumps back.

**Comment by nmccready** [comment]
Keep in mind the code was changed to use a copy of the model. This keeps from having recursive watch calls. Not sure if this is relevant.

**Comment by tombatossals** [comment]
I noticed this behaviour too, there are two examples which are affected:

http://tombatossals.github.io/angular-leaflet-directive/examples/0000-viewer.html#/markers/simple-example
http://tombatossals.github.io/angular-leaflet-directive/examples/0000-viewer.html#/markers/popup-example

I think having the marker position returned to the scope could be useful in many applications. @nmccready, can I take a look at this and try to solve it?

**Comment by nmccready** [comment]
Go for it @tombatossals

**Comment by jessertaylor** [comment]
I'm assuming this is fixed by eee69ed8f80d9793ab8a6eedc9993a712ac8a213

@tombatossals

**Comment by nmccready** [comment]
No this is not fixed. We may have to revert the copy / clone back to using the same reference. But then we are going to need to implement some tricky GTFO (get the f out) logic to keep the watches from spinning.

**Comment by nmccready** [comment]
This is where you problem begins https://github.com/tombatossals/angular-leaflet-directive/blob/master/src/directives/markers.js#L64-L68

**Comment by nmccready** [comment]
The change was made as destroy was being called constantly and markers were not being created when they were nested.

**Comment by nmccready** [comment]
I honestly would avoid this reliance anyways as watches slow everything down. Expecting angular to do this kind of work will only cause you problems later. There fore I suggest making the drag change and then getting the latest lObject via leafletData and do what you need with the new data.

**Comment by jessertaylor** [comment]
What is the reason for cloning the marker object? Personally I think the marker object should always be kept up to date - it seems to go against what Angular is about for me.

**Comment by nmccready** [comment]
You get unecessary digests and I was having markers not even being created as leafletMarkerHelpers was modifying the options of a model immediatley. IE as soon as it was created it was deleted. Again this  was happening in a few places as well. It happened again in geojson.js which had a race condition which required setting leafletData.setGeoJSON every time a change happened. 

I understand the angular purist point of view but it causes nothing but slowness, race conditions, and overly complicated code. I wonder if there can be a compromise. 

I would have to find the examples that break with reverting the model to a non-clone.

**Comment by bebud** [comment]
You can also watch for events on your marker (works for me):
```
$scope.$on('leafletDirectiveMarker.dragend', function (e, args) {
 myMarker.lng = args.model.lng;
 myMarker.lat = args.model.lat;
});
```

**Comment by nmccready** [comment]
Turns out this is not a bug; I'll have more info in the PR as the example is incorrect.

**Comment by nmccready** [comment]
#826

**Comment by CatchSandeepVaid** [comment]
I am facing the same issue and there is no workaround yet. Can someone please tell me a workaround for this?
